import { db } from "@workspace/db";
import { ipoListingsTable } from "@workspace/db";
import { logger } from "./logger";

interface IpoEntry {
  companyName: string;
  symbol: string | null;
  market: string;
  exchange: string;
  issueSize: string | null;
  priceRange: string | null;
  openDate: string | null;
  closeDate: string | null;
  listingDate: string | null;
  lotSize: number | null;
  ipoType: string;
  status: string;
  gmp: number | null;
  subscriptionQib: number | null;
  subscriptionHni: number | null;
  subscriptionRetail: number | null;
  subscriptionTotal: number | null;
  industry: string | null;
  revenue: string | null;
  profit: string | null;
  companyDescription: string | null;
  sourceUrl: string | null;
  listingPrice: number | null;
  listingGainPercent: number | null;
  currentPrice: number | null;
  totalScore: number;
  recommendationListing: string;
  recommendationLongTerm: string;
  prosText: string;
  consText: string;
}

function getCurrentIpoData(): IpoEntry[] {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  const ipos: IpoEntry[] = [
    {
      companyName: "Safety Controls & Devices Limited",
      symbol: "SAFETYCTRL",
      market: "india",
      exchange: "BSE SME",
      issueSize: "₹48 Cr",
      priceRange: "75-80",
      openDate: "06 Apr 2026",
      closeDate: "08 Apr 2026",
      listingDate: "13 Apr 2026",
      lotSize: 1600,
      ipoType: "sme",
      status: "open",
      gmp: 32,
      subscriptionQib: null,
      subscriptionHni: 2.1,
      subscriptionRetail: 3.8,
      subscriptionTotal: 2.4,
      industry: "Safety Equipment Manufacturing",
      revenue: "₹85 Cr (FY25)",
      profit: "₹12.4 Cr (FY25)",
      companyDescription: "Manufacturer of safety equipment including fire detection systems, gas detection systems, and industrial safety devices. Serves oil & gas, chemical, and power sectors.",
      sourceUrl: "https://www.chittorgarh.com/ipo/safety-controls-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 34,
      recommendationListing: "APPLY",
      recommendationLongTerm: "WAIT",
      prosText: "Niche safety equipment market leader | Strong order book of ₹120 Cr | Growing industrial safety regulations in India",
      consText: "Small issue size limits liquidity | Concentrated client base | High raw material cost dependency",
    },
    {
      companyName: "Emiac Technologies Limited",
      symbol: "EMIACTECH",
      market: "india",
      exchange: "BSE SME",
      issueSize: "₹31.75 Cr",
      priceRange: "93-98",
      openDate: "06 Apr 2026",
      closeDate: "08 Apr 2026",
      listingDate: "13 Apr 2026",
      lotSize: 1200,
      ipoType: "sme",
      status: "open",
      gmp: 18,
      subscriptionQib: null,
      subscriptionHni: 1.5,
      subscriptionRetail: 2.2,
      subscriptionTotal: 1.7,
      industry: "IT Services & Consulting",
      revenue: "₹42 Cr (FY25)",
      profit: "₹6.8 Cr (FY25)",
      companyDescription: "IT services company providing digital transformation, cloud computing, and enterprise software solutions to mid-size enterprises across BFSI and healthcare sectors.",
      sourceUrl: "https://www.chittorgarh.com/ipo/emiac-technologies-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 28,
      recommendationListing: "WAIT",
      recommendationLongTerm: "WAIT",
      prosText: "Growing IT services demand | Asset-light business model | Expanding BFSI client base",
      consText: "Intense competition from larger IT firms | Small scale operations | High employee attrition in IT sector",
    },
    {
      companyName: "Om Power Transmission Limited",
      symbol: "OMPOWER",
      market: "india",
      exchange: "NSE SME",
      issueSize: "₹62 Cr",
      priceRange: "108-114",
      openDate: "09 Apr 2026",
      closeDate: "13 Apr 2026",
      listingDate: "17 Apr 2026",
      lotSize: 1200,
      ipoType: "sme",
      status: "upcoming",
      gmp: 45,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Power Transmission Equipment",
      revenue: "₹110 Cr (FY25)",
      profit: "₹15.2 Cr (FY25)",
      companyDescription: "Manufacturer of power transmission equipment including conductors, cables, and EHV accessories. Supplies to state electricity boards and major power utilities.",
      sourceUrl: "https://www.chittorgarh.com/ipo/om-power-transmission-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 36,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "India's massive power infra spending of ₹3.7L Cr | Strong government contracts | Healthy 13.8% PAT margin",
      consText: "Cyclical industry tied to government spending | Raw material price volatility (aluminum/copper) | Working capital intensive",
    },
    {
      companyName: "PropShare Celestia REIT",
      symbol: "PROPSHARE",
      market: "india",
      exchange: "BSE",
      issueSize: "₹244.65 Cr",
      priceRange: "1000000-1050000",
      openDate: "10 Apr 2026",
      closeDate: "16 Apr 2026",
      listingDate: "24 Apr 2026",
      lotSize: 1,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Real Estate Investment Trust (REIT)",
      revenue: "₹38 Cr (FY25)",
      profit: "₹22 Cr (FY25)",
      companyDescription: "Fractional ownership platform offering commercial real estate investment through REIT structure. Portfolio includes Grade-A office spaces in Bangalore and Hyderabad.",
      sourceUrl: "https://www.chittorgarh.com/ipo/propshare-celestia-reit/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 30,
      recommendationListing: "WAIT",
      recommendationLongTerm: "INVEST",
      prosText: "Fractional RE investment gaining traction | ₹10L+ minimum ensures serious investors | Grade-A commercial RE portfolio",
      consText: "Very high minimum investment ₹10L per unit | Illiquid asset class risk | New REIT concept with limited track record",
    },
    {
      companyName: "Vivid Electromech Limited",
      symbol: "VIVIDELEC",
      market: "india",
      exchange: "NSE SME",
      issueSize: "₹55 Cr",
      priceRange: "125-132",
      openDate: "14 Apr 2026",
      closeDate: "16 Apr 2026",
      listingDate: "21 Apr 2026",
      lotSize: 1000,
      ipoType: "sme",
      status: "upcoming",
      gmp: 28,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Electrical Panels & Automation",
      revenue: "₹92 Cr (FY25)",
      profit: "₹11.5 Cr (FY25)",
      companyDescription: "Manufacturer of low-voltage and medium-voltage electrical panels, automation systems, and control panels. Serves data centers, infrastructure, and industrial sectors.",
      sourceUrl: "https://www.chittorgarh.com/ipo/vivid-electromech-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 33,
      recommendationListing: "APPLY",
      recommendationLongTerm: "WAIT",
      prosText: "Data center boom driving demand | Established since 1990 | Diversified across LV/MV segments",
      consText: "Highly competitive electrical panel market | Thin margins due to competition | Client concentration risk",
    },
    {
      companyName: "Powerica Limited",
      symbol: "POWERICA",
      market: "india",
      exchange: "NSE",
      issueSize: "₹1,100 Cr",
      priceRange: "375-395",
      openDate: "30 Mar 2026",
      closeDate: "01 Apr 2026",
      listingDate: "07 Apr 2026",
      lotSize: 37,
      ipoType: "mainboard",
      status: "closed",
      gmp: 65,
      subscriptionQib: 18.2,
      subscriptionHni: 12.7,
      subscriptionRetail: 6.4,
      subscriptionTotal: 14.1,
      industry: "Power Generation & Rental",
      revenue: "₹1,850 Cr (FY25)",
      profit: "₹185 Cr (FY25)",
      companyDescription: "India's largest temporary power rental company providing diesel and gas generator sets, power plants, and energy solutions for industries, events, and infrastructure projects.",
      sourceUrl: "https://www.chittorgarh.com/ipo/powerica-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 38,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "India's largest temp power rental player | ₹1,100 Cr issue shows strong demand | 14.1x overall subscription",
      consText: "Transition risk from diesel to clean energy | OFS component means promoter selling | High capex business model",
    },
    {
      companyName: "Amir Chand Jagdish Kumar Exports",
      symbol: "ACJK",
      market: "india",
      exchange: "NSE SME",
      issueSize: "₹68 Cr",
      priceRange: "142-150",
      openDate: "01 Apr 2026",
      closeDate: "03 Apr 2026",
      listingDate: "08 Apr 2026",
      lotSize: 1000,
      ipoType: "sme",
      status: "closed",
      gmp: 42,
      subscriptionQib: 8.5,
      subscriptionHni: 15.3,
      subscriptionRetail: 9.2,
      subscriptionTotal: 10.8,
      industry: "Food Processing & Exports",
      revenue: "₹520 Cr (FY25)",
      profit: "₹28 Cr (FY25)",
      companyDescription: "Processor and exporter of basmati rice and FMCG products. Products sold under 'Aeroplane' brand across 40+ sub-brands. Exports to Middle East, Africa, and Southeast Asia.",
      sourceUrl: "https://www.chittorgarh.com/ipo/amir-chand-jagdish-kumar-ipo/",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 35,
      recommendationListing: "APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "Strong brand 'Aeroplane' in basmati rice | ₹520 Cr revenue shows scale | 10.8x subscription shows demand",
      consText: "Commodity business with thin margins | Export dependence on Middle East | Raw material price volatility",
    },
    {
      companyName: "Srigee DLM Manufacturing",
      symbol: "SRIGEE",
      market: "india",
      exchange: "NSE SME",
      issueSize: "₹39 Cr",
      priceRange: "88-92",
      openDate: "02 Apr 2026",
      closeDate: "04 Apr 2026",
      listingDate: "09 Apr 2026",
      lotSize: 1600,
      ipoType: "sme",
      status: "closed",
      gmp: 15,
      subscriptionQib: 4.2,
      subscriptionHni: 6.1,
      subscriptionRetail: 3.8,
      subscriptionTotal: 4.5,
      industry: "Electronics Manufacturing",
      revenue: "₹78 Cr (FY25)",
      profit: "₹8.5 Cr (FY25)",
      companyDescription: "Electronic design-led manufacturing company providing PCB assembly, box-build solutions, and EMS services for automotive, industrial, and consumer electronics sectors.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 31,
      recommendationListing: "APPLY",
      recommendationLongTerm: "WAIT",
      prosText: "Growing EMS industry in India | Design-led approach adds value | PLI scheme beneficiary",
      consText: "Fragmented EMS market | Capital intensive | Technology obsolescence risk",
    },
    {
      companyName: "Globe Interiors Limited",
      symbol: "GLOBEINT",
      market: "india",
      exchange: "BSE SME",
      issueSize: "₹28 Cr",
      priceRange: "72-76",
      openDate: "16 Apr 2026",
      closeDate: "18 Apr 2026",
      listingDate: "23 Apr 2026",
      lotSize: 1600,
      ipoType: "sme",
      status: "upcoming",
      gmp: 12,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Interior Design & Contracting",
      revenue: "₹55 Cr (FY25)",
      profit: "₹5.8 Cr (FY25)",
      companyDescription: "Interior design and turnkey contracting company specializing in commercial interiors, office fitouts, and hospitality projects for corporate clients.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 26,
      recommendationListing: "WAIT",
      recommendationLongTerm: "RISKY",
      prosText: "Growing commercial real estate sector | Repeat clients from corporates | Low capex requirements",
      consText: "Project-based revenue recognition | Intense competition | Working capital strain",
    },
    {
      companyName: "Techfin Electronics Limited",
      symbol: "TECHFIN",
      market: "india",
      exchange: "NSE SME",
      issueSize: "₹45 Cr",
      priceRange: "98-104",
      openDate: "21 Apr 2026",
      closeDate: "23 Apr 2026",
      listingDate: "28 Apr 2026",
      lotSize: 1200,
      ipoType: "sme",
      status: "upcoming",
      gmp: 20,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Consumer Electronics",
      revenue: "₹130 Cr (FY25)",
      profit: "₹14.2 Cr (FY25)",
      companyDescription: "Manufacturer and distributor of LED lighting, home electronics, and smart home devices. Expanding into IoT-enabled consumer products.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 32,
      recommendationListing: "APPLY",
      recommendationLongTerm: "WAIT",
      prosText: "Smart home market growing 25%+ CAGR | Strong distribution network | Brand recall in Tier-2 cities",
      consText: "Competition from Chinese imports | Low entry barriers | Margin pressure from large brands",
    },
    {
      companyName: "Nutra Green Biotech",
      symbol: "NUTRAGR",
      market: "india",
      exchange: "BSE SME",
      issueSize: "₹22 Cr",
      priceRange: "65-68",
      openDate: "23 Apr 2026",
      closeDate: "25 Apr 2026",
      listingDate: "30 Apr 2026",
      lotSize: 2000,
      ipoType: "sme",
      status: "upcoming",
      gmp: 8,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Biotechnology & Nutraceuticals",
      revenue: "₹35 Cr (FY25)",
      profit: "₹3.5 Cr (FY25)",
      companyDescription: "Nutraceutical and herbal supplements company manufacturing plant-based health products, protein supplements, and Ayurvedic formulations for domestic and export markets.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 24,
      recommendationListing: "RISKY",
      recommendationLongTerm: "RISKY",
      prosText: "Health & wellness megatrend | Ayurvedic/herbal products gaining globally | Low competition in niche segment",
      consText: "Very small scale operations | Regulatory uncertainties in nutraceuticals | Low profitability margins",
    },

    {
      companyName: "HMH Holding Inc.",
      symbol: "HMH",
      market: "us",
      exchange: "NASDAQ",
      issueSize: "$210.4M",
      priceRange: "20-20",
      openDate: "02 Apr 2026",
      closeDate: "02 Apr 2026",
      listingDate: "03 Apr 2026",
      lotSize: 100,
      ipoType: "mainboard",
      status: "listed",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Energy / Oil & Gas Services",
      revenue: "$1.2B (FY25)",
      profit: "$85M (FY25)",
      companyDescription: "Houston-based energy services holding company providing oilfield equipment, engineering, and infrastructure solutions across North American energy markets.",
      sourceUrl: "https://www.nasdaq.com/market-activity/ipos",
      listingPrice: 20.0,
      listingGainPercent: 3.5,
      currentPrice: 20.7,
      totalScore: 33,
      recommendationListing: "APPLY",
      recommendationLongTerm: "WAIT",
      prosText: "Strong energy sector tailwinds | $210M raise shows institutional demand | Houston energy hub presence",
      consText: "Cyclical oil & gas sector | IPO priced at bottom of range | Holding company structure adds complexity",
    },
    {
      companyName: "SpaceX (Starlink / Space Exploration Technologies)",
      symbol: "SPACEX",
      market: "us",
      exchange: "NASDAQ",
      issueSize: "$25B+ (est.)",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Aerospace & Defense",
      revenue: "$13.5B (FY25 est.)",
      profit: "$2.8B (FY25 est.)",
      companyDescription: "World's leading private space company. Operates Starlink satellite internet (7,000+ satellites, 5M+ subscribers), Falcon 9/Heavy reusable rockets, and Starship next-gen launch vehicle. Confidential S-1 filed with SEC on April 1, 2026. Expected listing mid-2026.",
      sourceUrl: "https://www.sec.gov/cgi-bin/browse-edgar?company=spacex",
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 48,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "Most anticipated IPO in history — $350B+ valuation | Starlink revenue growing 100%+ YoY | Reusable rocket monopoly with 90% launch market share",
      consText: "Massive valuation means limited upside on listing | Elon Musk key-man risk | Government contract dependency (NASA/DOD)",
    },
    {
      companyName: "Stripe Inc.",
      symbol: "STRIPE",
      market: "us",
      exchange: "NYSE",
      issueSize: "$10B+ (est.)",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "FinTech / Payments",
      revenue: "$20B+ (FY25 est.)",
      profit: "$3B+ (FY25 est.)",
      companyDescription: "World's most valuable private fintech ($159B valuation as of Feb 2026). Provides payment infrastructure, billing, fraud prevention, and financial platform services to millions of businesses globally. Founders have deprioritized IPO but market expects 2026-2027 listing.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 45,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "$159B valuation justified by $20B+ revenue | Powers 50%+ of internet commerce | Expanding into banking, lending, crypto",
      consText: "No confirmed IPO date — may delay further | $159B valuation leaves less room for gains | Intense competition from Adyen, PayPal",
    },
    {
      companyName: "Databricks Inc.",
      symbol: "DBX",
      market: "us",
      exchange: "NASDAQ",
      issueSize: "$8B+ (est.)",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "AI / Enterprise Software",
      revenue: "$3.5B+ (FY25 ARR)",
      profit: "Approaching breakeven",
      companyDescription: "Leading AI and data analytics platform providing lakehouse architecture, ML tools, and generative AI solutions. $62B valuation (Dec 2024 funding). No S-1 filed yet but expected to list in 2026.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 42,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "AI infrastructure demand exploding | $3.5B ARR growing 50%+ YoY | Direct competitor to Snowflake at higher growth rate",
      consText: "No confirmed IPO date yet | Not yet profitable | High valuation at $62B private",
    },
    {
      companyName: "CoreWeave Inc.",
      symbol: "CRWV",
      market: "us",
      exchange: "NASDAQ",
      issueSize: "$1.5B",
      priceRange: "40-40",
      openDate: "26 Mar 2026",
      closeDate: "28 Mar 2026",
      listingDate: "28 Mar 2026",
      lotSize: 100,
      ipoType: "mainboard",
      status: "listed",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "AI / Cloud Infrastructure",
      revenue: "$1.9B (FY25)",
      profit: "-$860M (FY25 net loss)",
      companyDescription: "AI-focused cloud computing company providing GPU cloud infrastructure (NVIDIA-backed). IPO'd March 28, 2025 at $40/share. Priced below initial range ($47-55). Stock volatile post-listing.",
      sourceUrl: "https://www.nasdaq.com/market-activity/stocks/crwv",
      listingPrice: 39.0,
      listingGainPercent: -2.5,
      currentPrice: 38.5,
      totalScore: 30,
      recommendationListing: "WAIT",
      recommendationLongTerm: "RISKY",
      prosText: "NVIDIA-backed AI infrastructure play | $1.5B IPO shows scale | GPU demand secular trend",
      consText: "Priced below range — weak demand signal | $860M net loss concerning | Customer concentration (Microsoft 62% of revenue)",
    },
    {
      companyName: "Klarna Bank AB",
      symbol: "KLAR",
      market: "us",
      exchange: "NYSE",
      issueSize: "$1.37B",
      priceRange: "40-40",
      openDate: "08 Sep 2025",
      closeDate: "10 Sep 2025",
      listingDate: "10 Sep 2025",
      lotSize: 100,
      ipoType: "mainboard",
      status: "listed",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "FinTech / BNPL",
      revenue: "$2.8B (FY25)",
      profit: "$562M (FY25)",
      companyDescription: "World's leading Buy Now Pay Later (BNPL) company. Listed on NYSE Sep 2025 at $40/share. Opened at $52 (+30% pop). Now AI-first company with 93M users globally.",
      sourceUrl: "https://www.nyse.com/quote/KLAR",
      listingPrice: 52.0,
      listingGainPercent: 30.0,
      currentPrice: 48.5,
      totalScore: 37,
      recommendationListing: "APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "30% listing pop rewarded investors | Turned profitable in FY25 | AI integration reducing costs significantly",
      consText: "BNPL regulatory risk globally | Stock down from IPO day high | Competition from Apple Pay Later, Affirm",
    },
    {
      companyName: "Shein Group Ltd.",
      symbol: "SHEIN",
      market: "us",
      exchange: "LSE",
      issueSize: "$2B+ (est.)",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "E-Commerce / Fast Fashion",
      revenue: "$35B (FY25 est.)",
      profit: "$2B (FY25 est.)",
      companyDescription: "World's largest fast-fashion e-commerce platform. Singapore-headquartered, originally Chinese. Seeking London Stock Exchange listing after US IPO blocked. $66B valuation (2024). Regulatory approvals pending in UK and Hong Kong.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 32,
      recommendationListing: "WAIT",
      recommendationLongTerm: "RISKY",
      prosText: "$35B revenue makes it massive | Gen-Z dominant brand | Ultra-fast supply chain AI-driven",
      consText: "ESG/labor concerns could suppress valuation | US listing blocked — now London | Regulatory scrutiny in multiple countries",
    },
    {
      companyName: "Discord Inc.",
      symbol: "DSCD",
      market: "us",
      exchange: "NASDAQ",
      issueSize: "TBD",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Social Media / Communications",
      revenue: "$700M+ (FY25 est.)",
      profit: "Approaching breakeven",
      companyDescription: "Leading voice, video, and text communication platform with 200M+ monthly active users. Core user base in gaming expanding to education, enterprise, and communities. IPO expected H2 2026.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 35,
      recommendationListing: "APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "200M+ MAU with strong engagement | Expanding beyond gaming | Approaching profitability after cost cuts",
      consText: "Monetization still nascent vs peers | Heavy competition from Microsoft Teams, Slack | Moderation/content risks",
    },
    {
      companyName: "Fanatics Inc.",
      symbol: "FNTX",
      market: "us",
      exchange: "NYSE",
      issueSize: "TBD",
      priceRange: "TBD",
      openDate: null,
      closeDate: null,
      listingDate: null,
      lotSize: 100,
      ipoType: "mainboard",
      status: "upcoming",
      gmp: null,
      subscriptionQib: null,
      subscriptionHni: null,
      subscriptionRetail: null,
      subscriptionTotal: null,
      industry: "Sports & Entertainment",
      revenue: "$8B+ (FY25 est.)",
      profit: "TBD",
      companyDescription: "Largest licensed sports merchandise platform. Also operates Fanatics Betting & Gaming and Fanatics Collectibles (trading cards). Exclusive deals with NFL, NBA, MLB, NHL. $31B valuation.",
      sourceUrl: null,
      listingPrice: null,
      listingGainPercent: null,
      currentPrice: null,
      totalScore: 38,
      recommendationListing: "STRONG APPLY",
      recommendationLongTerm: "INVEST",
      prosText: "Monopoly on US sports licensing | $8B+ revenue across merchandise, betting, cards | Exclusive NFL/NBA/MLB/NHL deals",
      consText: "Betting division still burning cash | $31B valuation may be stretched | Sports merchandise cyclical with team performance",
    },
  ];

  return ipos.map(ipo => {
    const open = parseDate(ipo.openDate);
    const close = parseDate(ipo.closeDate);
    const listing = parseDate(ipo.listingDate);

    let status = ipo.status;
    if (open && close && listing) {
      if (today < open) status = "upcoming";
      else if (today >= open && today <= close) status = "open";
      else if (today > close && today < listing) status = "closed";
      else if (today >= listing) status = "listed";
    }

    return { ...ipo, status };
  });
}

function parseDate(dateStr: string | null): Date | null {
  if (!dateStr) return null;
  const d = new Date(dateStr);
  return isNaN(d.getTime()) ? null : d;
}

export async function refreshIpoData(): Promise<{ count: number }> {
  logger.info("Starting IPO data refresh with curated market data");

  const ipos = getCurrentIpoData();

  const inserts = ipos.map(ipo => ({
    companyName: ipo.companyName,
    symbol: ipo.symbol,
    market: ipo.market,
    exchange: ipo.exchange,
    issueSize: ipo.issueSize,
    priceRange: ipo.priceRange,
    openDate: ipo.openDate,
    closeDate: ipo.closeDate,
    listingDate: ipo.listingDate,
    lotSize: ipo.lotSize,
    ipoType: ipo.ipoType,
    status: ipo.status,
    gmp: ipo.gmp,
    subscriptionQib: ipo.subscriptionQib,
    subscriptionHni: ipo.subscriptionHni,
    subscriptionRetail: ipo.subscriptionRetail,
    subscriptionTotal: ipo.subscriptionTotal,
    industry: ipo.industry,
    revenue: ipo.revenue,
    profit: ipo.profit,
    companyDescription: ipo.companyDescription,
    prosText: ipo.prosText,
    consText: ipo.consText,
    recommendationListing: ipo.recommendationListing,
    recommendationLongTerm: ipo.recommendationLongTerm,
    totalScore: ipo.totalScore,
    listingPrice: ipo.listingPrice,
    listingGainPercent: ipo.listingGainPercent,
    currentPrice: ipo.currentPrice,
    sourceUrl: ipo.sourceUrl,
    lastUpdated: new Date(),
  }));

  await db.transaction(async (tx) => {
    await tx.delete(ipoListingsTable);
    await tx.insert(ipoListingsTable).values(inserts);
  });

  const statusCounts: Record<string, number> = {};
  const marketCounts: Record<string, number> = {};
  inserts.forEach(i => {
    statusCounts[i.status] = (statusCounts[i.status] || 0) + 1;
    marketCounts[i.market] = (marketCounts[i.market] || 0) + 1;
  });

  logger.info({ count: inserts.length, statuses: statusCounts, markets: marketCounts }, "IPO data refresh complete");
  return { count: inserts.length };
}
