import { db } from "@workspace/db";
import {
  marketAssetsTable,
  economicIndicatorsTable,
  economicEventsTable,
  geopoliticalEventsTable,
  newsItemsTable,
  watchlistTable,
} from "@workspace/db";
import { logger } from "./logger";

export async function seedDatabase() {
  const existing = await db.select().from(marketAssetsTable);
  if (existing.length > 0) {
    logger.info("Database already seeded, skipping.");
    return;
  }

  logger.info("Seeding database...");

  await db.insert(marketAssetsTable).values([
    { symbol: "SPX", name: "S&P 500", category: "indices", price: 5123.41, change: 28.4, changePercent: 0.56, volume: "3.2B", currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "NDX", name: "NASDAQ 100", category: "indices", price: 18043.2, change: 124.6, changePercent: 0.70, volume: "1.8B", currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "DJI", name: "Dow Jones", category: "indices", price: 38742.1, change: -45.2, changePercent: -0.12, volume: "420M", currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "DAX", name: "DAX 40", category: "indices", price: 18281.4, change: -112.3, changePercent: -0.61, volume: "89M", currency: "EUR", country: "Germany", flag: "🇩🇪", marketCap: null },
    { symbol: "FTSE", name: "FTSE 100", category: "indices", price: 8023.7, change: 34.2, changePercent: 0.43, volume: "760M", currency: "GBP", country: "United Kingdom", flag: "🇬🇧", marketCap: null },
    { symbol: "N225", name: "Nikkei 225", category: "indices", price: 38947.0, change: 673.2, changePercent: 1.76, volume: "2.1B", currency: "JPY", country: "Japan", flag: "🇯🇵", marketCap: null },
    { symbol: "HSI", name: "Hang Seng", category: "indices", price: 17284.5, change: -234.1, changePercent: -1.34, volume: "1.4B", currency: "HKD", country: "China", flag: "🇭🇰", marketCap: null },
    { symbol: "SSEC", name: "Shanghai Composite", category: "indices", price: 3041.2, change: -18.7, changePercent: -0.61, volume: "980M", currency: "CNY", country: "China", flag: "🇨🇳", marketCap: null },
    { symbol: "CAC40", name: "CAC 40", category: "indices", price: 7963.4, change: 45.8, changePercent: 0.58, volume: "110M", currency: "EUR", country: "France", flag: "🇫🇷", marketCap: null },
    { symbol: "VIX", name: "CBOE Volatility Index", category: "indices", price: 18.42, change: -0.87, changePercent: -4.51, volume: null, currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },

    { symbol: "EURUSD", name: "EUR/USD", category: "currencies", price: 1.0847, change: 0.0012, changePercent: 0.11, volume: "82B", currency: "USD", country: "Eurozone", flag: "🇪🇺", marketCap: null },
    { symbol: "GBPUSD", name: "GBP/USD", category: "currencies", price: 1.2612, change: -0.0034, changePercent: -0.27, volume: "45B", currency: "USD", country: "United Kingdom", flag: "🇬🇧", marketCap: null },
    { symbol: "USDJPY", name: "USD/JPY", category: "currencies", price: 152.87, change: 0.43, changePercent: 0.28, volume: "68B", currency: "JPY", country: "Japan", flag: "🇯🇵", marketCap: null },
    { symbol: "DXY", name: "US Dollar Index", category: "currencies", price: 104.23, change: -0.18, changePercent: -0.17, volume: null, currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "USDCNY", name: "USD/CNY", category: "currencies", price: 7.2381, change: 0.0156, changePercent: 0.22, volume: "32B", currency: "CNY", country: "China", flag: "🇨🇳", marketCap: null },
    { symbol: "USDRUB", name: "USD/RUB", category: "currencies", price: 91.43, change: 1.23, changePercent: 1.36, volume: "8B", currency: "RUB", country: "Russia", flag: "🇷🇺", marketCap: null },
    { symbol: "USDTRY", name: "USD/TRY", category: "currencies", price: 32.14, change: 0.22, changePercent: 0.69, volume: "12B", currency: "TRY", country: "Turkey", flag: "🇹🇷", marketCap: null },

    { symbol: "XAUUSD", name: "Gold", category: "commodities", price: 2341.5, change: 12.3, changePercent: 0.53, volume: "180B", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "XAGUSD", name: "Silver", category: "commodities", price: 27.42, change: -0.31, changePercent: -1.12, volume: "12B", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "USOIL", name: "WTI Crude Oil", category: "commodities", price: 82.34, change: -1.23, changePercent: -1.47, volume: "980M", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "BRENT", name: "Brent Crude Oil", category: "commodities", price: 87.12, change: -1.45, changePercent: -1.64, volume: "1.2B", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "NATGAS", name: "Natural Gas", category: "commodities", price: 1.834, change: 0.043, changePercent: 2.40, volume: "420M", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "COPPER", name: "Copper", category: "commodities", price: 4.432, change: 0.087, changePercent: 2.00, volume: "32B", currency: "USD", country: null, flag: null, marketCap: null },
    { symbol: "WHEAT", name: "Wheat", category: "commodities", price: 583.25, change: -8.75, changePercent: -1.48, volume: "320M", currency: "USD", country: null, flag: null, marketCap: null },

    { symbol: "BTCUSD", name: "Bitcoin", category: "crypto", price: 67234.0, change: 1423.0, changePercent: 2.16, volume: "28B", currency: "USD", country: null, flag: null, marketCap: "1.32T" },
    { symbol: "ETHUSD", name: "Ethereum", category: "crypto", price: 3512.4, change: -78.3, changePercent: -2.18, volume: "12B", currency: "USD", country: null, flag: null, marketCap: "421B" },
    { symbol: "SOLUSD", name: "Solana", category: "crypto", price: 178.23, change: 8.42, changePercent: 4.96, volume: "3.2B", currency: "USD", country: null, flag: null, marketCap: "79B" },
    { symbol: "BNBUSD", name: "BNB", category: "crypto", price: 582.1, change: -12.4, changePercent: -2.09, volume: "1.8B", currency: "USD", country: null, flag: null, marketCap: "86B" },

    { symbol: "US10Y", name: "US 10-Year Treasury", category: "bonds", price: 4.487, change: 0.043, changePercent: 0.97, volume: null, currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "US2Y", name: "US 2-Year Treasury", category: "bonds", price: 4.823, change: 0.012, changePercent: 0.25, volume: null, currency: "USD", country: "United States", flag: "🇺🇸", marketCap: null },
    { symbol: "DE10Y", name: "German 10-Year Bund", category: "bonds", price: 2.413, change: -0.021, changePercent: -0.86, volume: null, currency: "EUR", country: "Germany", flag: "🇩🇪", marketCap: null },
    { symbol: "JP10Y", name: "Japan 10-Year JGB", category: "bonds", price: 0.743, change: 0.008, changePercent: 1.09, volume: null, currency: "JPY", country: "Japan", flag: "🇯🇵", marketCap: null },
  ]);

  await db.insert(economicIndicatorsTable).values([
    { country: "United States", countryCode: "US", flag: "🇺🇸", indicator: "gdp", value: 2.5, unit: "% YoY", previousValue: 3.4, change: -0.9, period: "Q4 2024", trend: "deteriorating", impact: "negative" },
    { country: "United States", countryCode: "US", flag: "🇺🇸", indicator: "inflation", value: 3.2, unit: "%", previousValue: 3.4, change: -0.2, period: "Mar 2025", trend: "improving", impact: "positive" },
    { country: "United States", countryCode: "US", flag: "🇺🇸", indicator: "unemployment", value: 3.9, unit: "%", previousValue: 3.7, change: 0.2, period: "Mar 2025", trend: "deteriorating", impact: "negative" },
    { country: "United States", countryCode: "US", flag: "🇺🇸", indicator: "interest-rate", value: 5.25, unit: "%", previousValue: 5.25, change: 0, period: "Apr 2025", trend: "stable", impact: "neutral" },
    { country: "Eurozone", countryCode: "EU", flag: "🇪🇺", indicator: "gdp", value: 0.4, unit: "% YoY", previousValue: 0.5, change: -0.1, period: "Q4 2024", trend: "deteriorating", impact: "negative" },
    { country: "Eurozone", countryCode: "EU", flag: "🇪🇺", indicator: "inflation", value: 2.4, unit: "%", previousValue: 2.6, change: -0.2, period: "Mar 2025", trend: "improving", impact: "positive" },
    { country: "Eurozone", countryCode: "EU", flag: "🇪🇺", indicator: "interest-rate", value: 4.0, unit: "%", previousValue: 4.25, change: -0.25, period: "Apr 2025", trend: "improving", impact: "positive" },
    { country: "China", countryCode: "CN", flag: "🇨🇳", indicator: "gdp", value: 5.2, unit: "% YoY", previousValue: 4.9, change: 0.3, period: "Q4 2024", trend: "improving", impact: "positive" },
    { country: "China", countryCode: "CN", flag: "🇨🇳", indicator: "inflation", value: 0.1, unit: "%", previousValue: 0.3, change: -0.2, period: "Mar 2025", trend: "deteriorating", impact: "negative" },
    { country: "Japan", countryCode: "JP", flag: "🇯🇵", indicator: "gdp", value: -0.1, unit: "% QoQ", previousValue: 0.4, change: -0.5, period: "Q4 2024", trend: "deteriorating", impact: "negative" },
    { country: "Japan", countryCode: "JP", flag: "🇯🇵", indicator: "inflation", value: 2.8, unit: "%", previousValue: 2.5, change: 0.3, period: "Mar 2025", trend: "deteriorating", impact: "negative" },
    { country: "Japan", countryCode: "JP", flag: "🇯🇵", indicator: "interest-rate", value: 0.1, unit: "%", previousValue: -0.1, change: 0.2, period: "Mar 2025", trend: "improving", impact: "positive" },
    { country: "United Kingdom", countryCode: "GB", flag: "🇬🇧", indicator: "inflation", value: 3.4, unit: "%", previousValue: 4.0, change: -0.6, period: "Feb 2025", trend: "improving", impact: "positive" },
    { country: "United Kingdom", countryCode: "GB", flag: "🇬🇧", indicator: "interest-rate", value: 5.25, unit: "%", previousValue: 5.25, change: 0, period: "Apr 2025", trend: "stable", impact: "neutral" },
    { country: "Germany", countryCode: "DE", flag: "🇩🇪", indicator: "gdp", value: -0.2, unit: "% YoY", previousValue: 0.1, change: -0.3, period: "Q4 2024", trend: "deteriorating", impact: "negative" },
    { country: "India", countryCode: "IN", flag: "🇮🇳", indicator: "gdp", value: 8.4, unit: "% YoY", previousValue: 7.6, change: 0.8, period: "Q4 2024", trend: "improving", impact: "positive" },
    { country: "Brazil", countryCode: "BR", flag: "🇧🇷", indicator: "inflation", value: 4.6, unit: "%", previousValue: 4.8, change: -0.2, period: "Mar 2025", trend: "improving", impact: "positive" },
    { country: "Turkey", countryCode: "TR", flag: "🇹🇷", indicator: "inflation", value: 67.1, unit: "%", previousValue: 72.3, change: -5.2, period: "Mar 2025", trend: "improving", impact: "positive" },
    { country: "Russia", countryCode: "RU", flag: "🇷🇺", indicator: "interest-rate", value: 16.0, unit: "%", previousValue: 15.0, change: 1.0, period: "Feb 2025", trend: "deteriorating", impact: "negative" },
  ]);

  const now = new Date();
  const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);

  await db.insert(economicEventsTable).values([
    { title: "US Non-Farm Payrolls", country: "United States", flag: "🇺🇸", indicator: "employment", scheduledAt: nextWeek, forecast: 210000, previous: 275000, actual: null, unit: "K", impact: "high", released: false },
    { title: "Fed Interest Rate Decision", country: "United States", flag: "🇺🇸", indicator: "interest-rate", scheduledAt: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000), forecast: 5.25, previous: 5.25, actual: null, unit: "%", impact: "high", released: false },
    { title: "ECB Rate Decision", country: "Eurozone", flag: "🇪🇺", indicator: "interest-rate", scheduledAt: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000), forecast: 3.75, previous: 4.0, actual: null, unit: "%", impact: "high", released: false },
    { title: "US CPI Inflation", country: "United States", flag: "🇺🇸", indicator: "inflation", scheduledAt: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000), forecast: 3.1, previous: 3.2, actual: null, unit: "%", impact: "high", released: false },
    { title: "China GDP Q1 2025", country: "China", flag: "🇨🇳", indicator: "gdp", scheduledAt: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000), forecast: 5.0, previous: 5.2, actual: null, unit: "% YoY", impact: "high", released: false },
    { title: "UK CPI Inflation", country: "United Kingdom", flag: "🇬🇧", indicator: "inflation", scheduledAt: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000), forecast: 3.2, previous: 3.4, actual: null, unit: "%", impact: "medium", released: false },
    { title: "Germany Industrial Production", country: "Germany", flag: "🇩🇪", indicator: "gdp", scheduledAt: yesterday, forecast: -0.4, previous: -0.6, actual: -0.2, unit: "% MoM", impact: "medium", released: true },
    { title: "Japan BoJ Rate Decision", country: "Japan", flag: "🇯🇵", indicator: "interest-rate", scheduledAt: yesterday, forecast: 0.1, previous: 0.1, actual: 0.1, unit: "%", impact: "high", released: true },
    { title: "US Initial Jobless Claims", country: "United States", flag: "🇺🇸", indicator: "unemployment", scheduledAt: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000), forecast: 212000, previous: 208000, actual: null, unit: "K", impact: "medium", released: false },
  ]);

  await db.insert(geopoliticalEventsTable).values([
    {
      title: "Russia-Ukraine War",
      description: "Ongoing full-scale invasion of Ukraine by Russian forces. Major frontline activity along eastern Ukraine. NATO support packages continuing. Global energy and grain markets severely impacted.",
      region: "Eastern Europe",
      countries: ["Russia", "Ukraine"],
      type: "war",
      severity: "critical",
      marketImpact: "Bearish energy (disruptions), bearish European equities, bullish defense stocks, bullish safe havens (gold, USD). Grain and fertilizer supply chains disrupted.",
      affectedAssets: ["XAUUSD", "NATGAS", "WHEAT", "DAX", "EURUSD", "USDRUB"],
      startDate: "2022-02-24",
      status: "active",
      casualtiesReported: true,
      economicLoss: "$500B+",
    },
    {
      title: "Israel-Hamas War / Gaza Conflict",
      description: "Military conflict between Israel and Hamas in Gaza. Regional escalation risk with Hezbollah (Lebanon) and Houthi attacks on Red Sea shipping. Iran-proxy involvement heightens risk of broader Middle East war.",
      region: "Middle East",
      countries: ["Israel", "Palestine", "Lebanon", "Yemen", "Iran"],
      type: "war",
      severity: "critical",
      marketImpact: "Bullish oil (supply risk), bullish defense, bullish gold. Bearish Red Sea shipping routes causing supply chain disruption. Risk-off sentiment in emerging markets.",
      affectedAssets: ["USOIL", "BRENT", "XAUUSD", "XAGUSD"],
      startDate: "2023-10-07",
      status: "escalating",
      casualtiesReported: true,
      economicLoss: "$50B+",
    },
    {
      title: "Taiwan Strait Tensions",
      description: "Increasing Chinese military exercises around Taiwan. US naval presence in the region. Technology supply chain risks as TSMC produces majority of world's advanced chips on the island.",
      region: "Asia-Pacific",
      countries: ["China", "Taiwan", "United States"],
      type: "conflict",
      severity: "high",
      marketImpact: "Bearish semiconductor stocks and tech. Risk to global supply chains. Bullish defense stocks. Safe haven demand elevated.",
      affectedAssets: ["NDX", "HSI", "SSEC", "BTCUSD"],
      startDate: "2022-08-01",
      status: "active",
      casualtiesReported: false,
      economicLoss: null,
    },
    {
      title: "US-China Trade War Escalation",
      description: "Expanding tariffs and technology export restrictions between US and China. Semiconductor export controls, investment restrictions. China retaliating with rare earth minerals and critical material restrictions.",
      region: "Global",
      countries: ["United States", "China"],
      type: "trade-dispute",
      severity: "high",
      marketImpact: "Bearish global trade volumes. Bearish tech and manufacturing. Bullish domestic production alternatives. Supply chain reconfiguration costs.",
      affectedAssets: ["SPX", "NDX", "SSEC", "HSI", "COPPER"],
      startDate: "2018-01-01",
      status: "escalating",
      casualtiesReported: false,
      economicLoss: "$500B+",
    },
    {
      title: "Iran Nuclear Program Tensions",
      description: "Iran continues uranium enrichment beyond treaty limits. US and EU sanctions in place. Military strikes threatened. Strait of Hormuz transit risk for oil shipments.",
      region: "Middle East",
      countries: ["Iran", "United States", "Israel", "Saudi Arabia"],
      type: "political-crisis",
      severity: "high",
      marketImpact: "Bullish oil prices (supply risk). Bullish defense stocks. Risk-off pressure on regional equities.",
      affectedAssets: ["USOIL", "BRENT", "XAUUSD"],
      startDate: "2021-06-01",
      status: "active",
      casualtiesReported: false,
      economicLoss: null,
    },
    {
      title: "North Korea Missile Tests",
      description: "DPRK conducting ballistic missile tests in violation of UN Security Council resolutions. Collaboration with Russia on weapons technology reported. Japan and South Korea on high alert.",
      region: "Asia-Pacific",
      countries: ["North Korea", "South Korea", "Japan"],
      type: "conflict",
      severity: "medium",
      marketImpact: "Bearish regional Asian equities during escalation. Bullish defense sector. Risk premium elevated in KRW and JPY.",
      affectedAssets: ["N225", "USDJPY"],
      startDate: "2022-01-01",
      status: "active",
      casualtiesReported: false,
      economicLoss: null,
    },
    {
      title: "Sudan Civil War",
      description: "Armed conflict between Sudanese Armed Forces and Rapid Support Forces. Humanitarian crisis with millions displaced. Gold mining and agricultural export disruptions.",
      region: "Africa",
      countries: ["Sudan"],
      type: "war",
      severity: "high",
      marketImpact: "Minimal direct market impact but contributes to humanitarian instability. Gold supply chain minor disruption.",
      affectedAssets: ["XAUUSD"],
      startDate: "2023-04-15",
      status: "active",
      casualtiesReported: true,
      economicLoss: "$10B+",
    },
  ]);

  await db.insert(newsItemsTable).values([
    {
      headline: "Fed Signals Rate Cut Delay as Inflation Remains Stubborn Above 3%",
      summary: "Federal Reserve officials indicate they need more evidence of cooling inflation before cutting rates. Market pricing for first cut shifted from June to September 2025. Bond yields rise on news.",
      source: "Reuters",
      category: "central-banks",
      impact: "high",
      sentiment: "bearish",
      region: "North America",
      affectedAssets: ["SPX", "NDX", "US10Y", "EURUSD", "XAUUSD"],
      marketConclusion: "Dollar bullish. Equities under pressure. Gold and bonds sell off. Emerging market currencies at risk. Higher-for-longer narrative strengthens.",
      isBreaking: true,
    },
    {
      headline: "Oil Prices Fall 2% as Houthi Threat to Red Sea Shipping Subsides",
      summary: "Brent crude drops after US naval operations successfully intercept Houthi drone attacks. Red Sea commercial traffic partially restoring. OPEC+ output cut compliance remains strong.",
      source: "Bloomberg",
      category: "commodities",
      impact: "high",
      sentiment: "bearish",
      region: "Middle East",
      affectedAssets: ["USOIL", "BRENT", "XAUUSD"],
      marketConclusion: "Short-term bearish oil. Shipping costs to normalize. Inflation relief in Europe as energy costs ease. Monitor OPEC+ production decisions.",
      isBreaking: false,
    },
    {
      headline: "China GDP Beats Expectations at 5.3% in Q1 2025",
      summary: "Chinese economy exceeds government growth target, driven by manufacturing and exports. Domestic consumption remains weak. Property sector still in distress. Stimulus measures beginning to show effect.",
      source: "South China Morning Post",
      category: "macro",
      impact: "high",
      sentiment: "bullish",
      region: "Asia-Pacific",
      affectedAssets: ["HSI", "SSEC", "COPPER", "USDCNY"],
      marketConclusion: "Bullish Hong Kong and China equities. Copper and industrial metals rally on demand outlook. CNY appreciation pressure. Risk-on for commodity exporters.",
      isBreaking: true,
    },
    {
      headline: "ECB Hints at June Rate Cut After Eurozone Inflation Falls to 2.4%",
      summary: "European Central Bank President signals readiness to cut rates in June if inflation data continues to cooperate. Eurozone growth remains fragile, particularly in Germany which saw negative GDP.",
      source: "Financial Times",
      category: "central-banks",
      impact: "high",
      sentiment: "bullish",
      region: "Europe",
      affectedAssets: ["DAX", "CAC40", "EURUSD", "DE10Y"],
      marketConclusion: "Bullish European equities. EUR under pressure vs USD. German bunds rally on rate cut expectations. Banking stocks face net interest margin compression.",
      isBreaking: false,
    },
    {
      headline: "Bitcoin Surges Past $67,000 on ETF Inflows and Halving Anticipation",
      summary: "Bitcoin spot ETFs see record weekly inflows of $2.4B. Upcoming halving event reduces miner supply. Institutional adoption accelerating with sovereign wealth funds now holding BTC.",
      source: "CoinDesk",
      category: "crypto",
      impact: "medium",
      sentiment: "bullish",
      region: null,
      affectedAssets: ["BTCUSD", "ETHUSD", "SOLUSD"],
      marketConclusion: "Crypto cycle entering acceleration phase. Risk-on indicator for broader markets. Monitor regulatory developments. Miner stocks beneficiary.",
      isBreaking: false,
    },
    {
      headline: "Japan Yen Hits 34-Year Low vs Dollar as BoJ Maintains Ultra-Low Rates",
      summary: "USD/JPY touches 153 as Bank of Japan signals continued patience despite inflation above target. Verbal intervention from Finance Ministry but no concrete action. Carry trade flourishing.",
      source: "Nikkei",
      category: "macro",
      impact: "high",
      sentiment: "neutral",
      region: "Asia-Pacific",
      affectedAssets: ["USDJPY", "N225"],
      marketConclusion: "Yen weakness boosts Japanese exporters and Nikkei. Risk of sudden BoJ intervention. Carry trade unwind risk elevated. Nikkei performance driven by weak yen rather than fundamentals.",
      isBreaking: true,
    },
    {
      headline: "NVIDIA Earnings Shatter Expectations: AI Demand Drives 122% Revenue Growth",
      summary: "NVIDIA reports quarterly revenue of $22.1B, far exceeding analyst estimates. Data center segment driven by AI chip demand from hyperscalers. Guidance raised for Q2 2025.",
      source: "CNBC",
      category: "earnings",
      impact: "high",
      sentiment: "bullish",
      region: "North America",
      affectedAssets: ["NDX", "SPX"],
      marketConclusion: "Mega-cap tech rally expected. AI infrastructure investment thesis validated. Semiconductor supply chain stocks benefit. Broad tech sector re-rating likely.",
      isBreaking: false,
    },
    {
      headline: "Russia-Ukraine War: Major Offensive Reported in Kharkiv Region",
      summary: "Russian forces launch significant offensive operations in northeastern Ukraine. Ukrainian defenses strained. US Congress debates additional military aid package of $61B.",
      source: "Reuters",
      category: "geopolitical",
      impact: "high",
      sentiment: "bearish",
      region: "Eastern Europe",
      affectedAssets: ["DAX", "EURUSD", "XAUUSD", "NATGAS", "WHEAT"],
      marketConclusion: "Risk-off for European assets. Natural gas and wheat supply risk premium rises. Gold safe haven demand increases. European defense stocks rally. EUR weakens.",
      isBreaking: true,
    },
    {
      headline: "India Emerges as Fastest Growing Major Economy with 8.4% GDP",
      summary: "India's GDP growth outpaces China for the second consecutive year. Manufacturing expansion driven by global supply chain diversification away from China. FDI inflows hit record high.",
      source: "The Hindu Business Line",
      category: "macro",
      impact: "medium",
      sentiment: "bullish",
      region: "Asia-Pacific",
      affectedAssets: ["SPX"],
      marketConclusion: "Bullish on India-exposed equities and funds. Supply chain diversification plays benefit. Emerging market positive sentiment. INR support expected.",
      isBreaking: false,
    },
    {
      headline: "OPEC+ Extends Oil Production Cuts Through Q3 2025",
      summary: "OPEC+ alliance extends 3.66 million barrels per day of production cuts through September 2025. Saudi Arabia and Russia lead compliance. Global oil inventories at multi-year lows.",
      source: "Bloomberg",
      category: "commodities",
      impact: "high",
      sentiment: "bullish",
      region: "Middle East",
      affectedAssets: ["USOIL", "BRENT", "XAUUSD"],
      marketConclusion: "Bullish oil medium-term. Inflationary pressure from energy costs. Bearish for rate-cut expectations. Petro-currency (CAD, NOK, RUB) positive.",
      isBreaking: false,
    },
  ]);

  await db.insert(watchlistTable).values([
    { symbol: "XAUUSD", name: "Gold", type: "asset", notes: "Geopolitical hedge. Watch for breakout above $2400." },
    { symbol: "USOIL", name: "WTI Crude Oil", type: "asset", notes: "OPEC+ cuts + Middle East tension = support." },
    { symbol: "US10Y", name: "US 10Y Treasury", type: "asset", notes: "Fed rate path proxy. Key for equity valuations." },
    { symbol: "Russia-Ukraine War", name: "Russia-Ukraine War", type: "event", notes: "Primary geopolitical risk driver for Europe." },
    { symbol: "US", name: "United States", type: "country", notes: "Fed policy, election cycle, AI capex." },
  ]);

  logger.info("Database seeded successfully.");
}
