services:
  - type: web
    name: globalpulse-api
    env: node
    buildCommand: npm install
    startCommand: node dist/index.mjs
    envVars:
      - key: PORT
        value: 3001
      - key: SELF_API_URL
        fromService:
          type: web
          name: globalpulse-api
          property: host
      - key: GROQ_API_KEY_BTC
        sync: false
      - key: GROQ_API_KEY_BTC2
        sync: false
      - key: GROQ_API_KEY_NIFTY
        sync: false
      - key: GROQ_API_KEY_USD
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: DATABASE_BACKUP_URL
        sync: false
